# Generated by Django 4.0.3 on 2023-02-05 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_title', models.CharField(max_length=100)),
                ('a_content', models.CharField(max_length=200)),
            ],
        ),
    ]
