# Generated by Django 4.0.3 on 2023-02-07 15:07

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_selfname', models.CharField(max_length=50)),
                ('a_companyname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_perperson', models.FloatField(default=0)),
                ('a_perday', models.FloatField(default=0)),
                ('a_perbooking', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AdvertCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_category', models.CharField(max_length=50)),
                ('a_rating', models.IntegerField(default=0)),
                ('a_description', models.CharField(max_length=500)),
                ('a_img', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to='')),
                ('a_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='book.name')),
                ('a_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='book.price')),
            ],
        ),
    ]
