# Generated by Django 4.0.3 on 2023-02-07 20:09

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_name_price_advertcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertcard',
            name='a_img',
            field=models.ImageField(upload_to=django.core.files.storage.FileSystemStorage(location='/media/photos')),
        ),
        migrations.AlterField(
            model_name='advertcard',
            name='a_rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
