# Generated by Django 4.0.3 on 2023-02-07 20:19

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_advertcard_a_img_alter_advertcard_a_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertcard',
            name='a_img',
            field=models.ImageField(upload_to=django.core.files.storage.FileSystemStorage(location='book/media/photos')),
        ),
    ]
