# Generated by Django 4.0.3 on 2023-02-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_advertcard_a_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertcard',
            name='a_img',
            field=models.ImageField(upload_to='book/media/photos'),
        ),
    ]
