# Generated by Django 4.0.3 on 2023-03-26 22:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_suggestion_offer_a_img_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_address', models.CharField(max_length=200)),
                ('a_city', models.CharField(max_length=100)),
                ('a_country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_message', models.CharField(default=0, max_length=100)),
                ('a_rating', models.PositiveIntegerField(blank=True, default=0)),
                ('a_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_roomNo', models.PositiveIntegerField(default=0)),
                ('is_booked', models.BooleanField(default=False)),
                ('a_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_category', models.CharField(blank=True, default='B Grade', max_length=10, null=True)),
                ('a_description', models.CharField(blank=True, max_length=150)),
                ('a_price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('a_tableNo', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('is_booked', models.BooleanField(default=False)),
                ('a_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='TableCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_category', models.CharField(blank=True, default='B Grade', max_length=10, null=True)),
                ('a_description', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='advertcard',
            name='a_rating',
        ),
        migrations.AddField(
            model_name='advertcard',
            name='a_detail',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='a_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertcard',
            name='a_category',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='advertcard',
            name='a_price',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.AddField(
            model_name='tablecategory',
            name='a_building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Resturant', to='book.advertcard'),
        ),
        migrations.AddField(
            model_name='table',
            name='a_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='book.tablecategory'),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='a_building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building', to='book.advertcard'),
        ),
        migrations.AddField(
            model_name='room',
            name='a_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='book.roomcategory'),
        ),
        migrations.AddField(
            model_name='review',
            name='a_advert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertCommentedOn', to='book.advertcard'),
        ),
        migrations.AddField(
            model_name='review',
            name='a_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advertcard',
            name='a_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='book.address'),
        ),
    ]
