# Generated by Django 4.2.2 on 2023-07-08 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_address_review_room_roomcategory_table_tablecategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='a_date',
            new_name='a_booked_till',
        ),
        migrations.AddField(
            model_name='address',
            name='a_zipcode',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_card_number', models.SmallIntegerField(max_length=20)),
                ('a_expiry_date', models.DateField()),
                ('a_cvc', models.SmallIntegerField(max_length=5)),
                ('a_holder_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardHolderName', to='book.name')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_request', models.CharField(blank=True, max_length=300, null=True)),
                ('a_arrival', models.TimeField(blank=True, null=True)),
                ('a_booker_phone_no', models.IntegerField(max_length=16, null=True)),
                ('a_booker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booker', to=settings.AUTH_USER_MODEL)),
                ('a_booker_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bokkerAddress', to='book.address')),
                ('a_booker_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookerCard', to='book.card')),
                ('a_bulding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place', to='book.advertcard')),
                ('a_guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest', to='book.name')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='a_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.booking'),
        ),
    ]
