# Generated by Django 4.2.2 on 2023-07-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_rename_a_date_room_a_booked_till_address_a_zipcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='a_booker_phone_no',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='a_card_number',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='a_cvc',
            field=models.SmallIntegerField(),
        ),
    ]
