# Generated by Django 4.2.2 on 2023-07-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_alter_booking_a_booker_phone_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='a_time_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
