# Generated by Django 4.2.2 on 2023-07-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_booking_a_time_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='a_price',
            field=models.IntegerField(null=True),
        ),
    ]
