# Generated by Django 4.2.2 on 2023-07-10 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_booking_a_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='a_price',
            new_name='a_payment',
        ),
    ]
