# Generated by Django 4.2.2 on 2023-07-11 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_room_a_booked_from_alter_room_a_booked_till'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='a_holder_name',
            field=models.CharField(max_length=50),
        ),
    ]
