# Generated by Django 4.2.2 on 2023-07-11 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_alter_booking_a_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='a_bulding',
        ),
        migrations.AddField(
            model_name='booking',
            name='a_building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place', to='book.advertcard'),
        ),
    ]
