# Generated by Django 4.2.2 on 2023-07-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0017_remove_booking_a_bulding_booking_a_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='a_booked_from',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='a_booked_till',
            field=models.DateField(null=True),
        ),
    ]
