# Generated by Django 4.2.2 on 2023-07-11 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0018_booking_a_booked_from_booking_a_booked_till"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="table",
            name="a_date",
        ),
        migrations.AddField(
            model_name="table",
            name="a_booked_from",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="table",
            name="a_booked_till",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="table",
            name="a_booking",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking",
                to="book.booking",
            ),
        ),
    ]
