# Generated by Django 4.2.2 on 2023-07-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0019_remove_table_a_date_table_a_booked_from_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="a_tableNo",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="table",
            name="is_booked",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
