# Generated by Django 4.2.2 on 2023-07-12 04:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0020_table_id_alter_table_a_tableno_alter_table_is_booked"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
                null=True,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="booking",
            name="a_booked_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="a_booked_till",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="a_payment",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
