# Generated by Django 4.2.2 on 2023-07-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0022_advertcard_is_booked_alter_booking_a_booker_card_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='a_advert',
            new_name='a_building',
        ),
        migrations.AddField(
            model_name='booking',
            name='a_finsished',
            field=models.BooleanField(default=False),
        ),
    ]
