# Generated by Django 4.2.2 on 2023-07-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0023_rename_a_advert_review_a_building_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertcard',
            name='a_rating',
            field=models.FloatField(default=0, null=True),
        ),
    ]
