# Generated by Django 4.2.2 on 2023-07-19 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0024_advertcard_a_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_wifi', models.BooleanField(default=False)),
                ('a_parking', models.BooleanField(default=False)),
                ('a_family_rooms', models.BooleanField(default=False)),
                ('a_room_service', models.BooleanField(default=False)),
                ('a_fitness', models.BooleanField(default=False)),
                ('a_bar', models.BooleanField(default=False)),
                ('a_pool', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='a_guests',
            field=models.SmallIntegerField(default=2, null=True),
        ),
        migrations.AddField(
            model_name='tablecategory',
            name='a_table_for',
            field=models.SmallIntegerField(default=2, null=True),
        ),
        migrations.AddField(
            model_name='advertcard',
            name='a_facilites',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='book.facilities'),
        ),
    ]
