# Generated by Django 4.2.2 on 2023-07-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0025_facilities_roomcategory_a_guests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertcard',
            name='is_visited',
            field=models.BooleanField(default=False),
        ),
    ]
